spring.datasource.url=jdbc:mysql://mediplus-mysql.mysql.database.azure.com:3306/healthcare_db?useSSL=true&requireSSL=true
spring.datasource.username=rootadmin
spring.datasource.password=MediPlus2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB